<a href="https://colab.research.google.com/github/chiyeon01/ML_CONTEST/blob/main/DACON/%EC%8B%A0%EC%9A%A9%EC%B9%B4%EB%93%9C%20%EA%B3%A0%EA%B0%9D%20%EC%84%B8%EA%B7%B8%EB%A8%BC%ED%8A%B8%20%EB%B6%84%EB%A5%98%20AI%20%EA%B2%BD%EC%A7%84%EB%8C%80%ED%9A%8C/1.%20member_info_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

In [ ]:
!unzip '/content/gdrive/MyDrive/Colab Notebooks/z.대회 & 프로젝트/2025_신용카드 고객 세그먼트 분류_DACON/open.zip'

Archive:  /content/gdrive/MyDrive/Colab Notebooks/z.대회 & 프로젝트/2025_신용카드 고객 세그먼트 분류_DACON/open.zip
   creating: test/
   creating: test/1.회원정보/
  inflating: test/1.회원정보/201807_test_회원정보.parquet
  inflating: test/1.회원정보/201808_test_회원정보.parquet
  inflating: test/1.회원정보/201809_test_회원정보.parquet
  inflating: test/1.회원정보/201810_test_회원정보.parquet
  inflating: test/1.회원정보/201811_test_회원정보.parquet
  inflating: test/1.회원정보/201812_test_회원정보.parquet
   creating: test/2.신용정보/
  inflating: test/2.신용정보/201807_test_신용정보.parquet
  inflating: test/2.신용정보/201808_test_신용정보.parquet
  inflating: test/2.신용정보/201809_test_신용정보.parquet
  inflating: test/2.신용정보/201810_test_신용정보.parquet
  inflating: test/2.신용정보/201811_test_신용정보.parquet
  inflating: test/2.신용정보/201812_test_신용정보.parquet
   creating: test/3.승인매출정보/
  inflating: test/3.승인매출정보/201807_test_승인매출정보.parquet
  inflating: test/3.승인매출정보/201808_test_승인매출정보.parquet
  inflating: test/3.승인매출정보/201809_test_승인매출정보.parquet
  inflating: test/3.승인매출정보/201810_test_승인매출정보.parquet
  inflating: test/3.승인매출정보/201811_test_승인매출정보.parquet
  inflating: test/3.승인매출정보/201812_test_승인매출정보.parquet
   creating: test/4.청구입금정보/
  inflating: test/4.청구입금정보/201807_test_청구정보.parquet
  inflating: test/4.청구입금정보/201808_test_청구정보.parquet
  inflating: test/4.청구입금정보/201809_test_청구정보.parquet
  inflating: test/4.청구입금정보/201810_test_청구정보.parquet
  inflating: test/4.청구입금정보/201811_test_청구정보.parquet
  inflating: test/4.청구입금정보/201812_test_청구정보.parquet
   creating: test/5.잔액정보/
  inflating: test/5.잔액정보/201807_test_잔액정보.parquet
  inflating: test/5.잔액정보/201808_test_잔액정보.parquet
  inflating: test/5.잔액정보/201809_test_잔액정보.parquet
  inflating: test/5.잔액정보/201810_test_잔액정보.parquet
  inflating: test/5.잔액정보/201811_test_잔액정보.parquet
  inflating: test/5.잔액정보/201812_test_잔액정보.parquet
   creating: test/6.채널정보/
  inflating: test/6.채널정보/201807_test_채널정보.parquet
  inflating: test/6.채널정보/201808_test_채널정보.parquet
  inflating: test/6.채널정보/201809_test_채널정보.parquet
  inflating: test/6.채널정보/201810_test_채널정보.parquet
  inflating: test/6.채널정보/201811_test_채널정보.parquet
  inflating: test/6.채널정보/201812_test_채널정보.parquet
   creating: test/7.마케팅정보/
  inflating: test/7.마케팅정보/201807_test_마케팅정보.parquet
  inflating: test/7.마케팅정보/201808_test_마케팅정보.parquet
  inflating: test/7.마케팅정보/201809_test_마케팅정보.parquet
  inflating: test/7.마케팅정보/201810_test_마케팅정보.parquet
  inflating: test/7.마케팅정보/201811_test_마케팅정보.parquet
  inflating: test/7.마케팅정보/201812_test_마케팅정보.parquet
   creating: test/8.성과정보/
  inflating: test/8.성과정보/201807_test_성과정보.parquet
  inflating: test/8.성과정보/201808_test_성과정보.parquet
  inflating: test/8.성과정보/201809_test_성과정보.parquet
  inflating: test/8.성과정보/201810_test_성과정보.parquet
  inflating: test/8.성과정보/201811_test_성과정보.parquet
  inflating: test/8.성과정보/201812_test_성과정보.parquet
   creating: train/
   creating: train/1.회원정보/
  inflating: train/1.회원정보/201807_train_회원정보.parquet
  inflating: train/1.회원정보/201808_train_회원정보.parquet
  inflating: train/1.회원정보/201809_train_회원정보.parquet
  inflating: train/1.회원정보/201810_train_회원정보.parquet
  inflating: train/1.회원정보/201811_train_회원정보.parquet
  inflating: train/1.회원정보/201812_train_회원정보.parquet
   creating: train/2.신용정보/
  inflating: train/2.신용정보/201807_train_신용정보.parquet
  inflating: train/2.신용정보/201808_train_신용정보.parquet
  inflating: train/2.신용정보/201809_train_신용정보.parquet
  inflating: train/2.신용정보/201810_train_신용정보.parquet
  inflating: train/2.신용정보/201811_train_신용정보.parquet
  inflating: train/2.신용정보/201812_train_신용정보.parquet
   creating: train/3.승인매출정보/
  inflating: train/3.승인매출정보/201807_train_승인매출정보.parquet
  inflating: train/3.승인매출정보/201808_train_승인매출정보.parquet
  inflating: train/3.승인매출정보/201809_train_승인매출정보.parquet
  inflating: train/3.승인매출정보/201810_train_승인매출정보.parquet
  inflating: train/3.승인매출정보/201811_train_승인매출정보.parquet
  inflating: train/3.승인매출정보/201812_train_승인매출정보.parquet
   creating: train/4.청구입금정보/
  inflating: train/4.청구입금정보/201807_train_청구정보.parquet
  inflating: train/4.청구입금정보/201808_train_청구정보.parquet
  inflating: train/4.청구입금정보/201809_train_청구정보.parquet
  inflating: train/4.청구입금정보/201810_train_청구정보.parquet
  inflating: train/4.청구입금정보/201811_train_청구정보.parquet
  inflating: train/4.청구입금정보/201812_train_청구정보.parquet
   creating: train/5.잔액정보/
  inflating: train/5.잔액정보/201807_train_잔액정보.parquet
  inflating: train/5.잔액정보/201808_train_잔액정보.parquet
  inflating: train/5.잔액정보/201809_train_잔액정보.parquet
  inflating: train/5.잔액정보/201810_train_잔액정보.parquet
  inflating: train/5.잔액정보/201811_train_잔액정보.parquet
  inflating: train/5.잔액정보/201812_train_잔액정보.parquet
   creating: train/6.채널정보/
  inflating: train/6.채널정보/201807_train_채널정보.parquet
  inflating: train/6.채널정보/201808_train_채널정보.parquet
  inflating: train/6.채널정보/201809_train_채널정보.parquet
  inflating: train/6.채널정보/201810_train_채널정보.parquet
  inflating: train/6.채널정보/201811_train_채널정보.parquet
  inflating: train/6.채널정보/201812_train_채널정보.parquet
   creating: train/7.마케팅정보/
  inflating: train/7.마케팅정보/201807_train_마케팅정보.parquet
  inflating: train/7.마케팅정보/201808_train_마케팅정보.parquet
  inflating: train/7.마케팅정보/201809_train_마케팅정보.parquet
  inflating: train/7.마케팅정보/201810_train_마케팅정보.parquet
  inflating: train/7.마케팅정보/201811_train_마케팅정보.parquet
  inflating: train/7.마케팅정보/201812_train_마케팅정보.parquet
   creating: train/8.성과정보/
  inflating: train/8.성과정보/201807_train_성과정보.parquet
  inflating: train/8.성과정보/201808_train_성과정보.parquet
  inflating: train/8.성과정보/201809_train_성과정보.parquet
  inflating: train/8.성과정보/201810_train_성과정보.parquet
  inflating: train/8.성과정보/201811_train_성과정보.parquet
  inflating: train/8.성과정보/201812_train_성과정보.parquet
  inflating: sample_submission.csv
  inflating: 신용카드 고객 세그먼트 분류 AI 경진대회 데이터 명세.xlsx

In [ ]:
train_member_info_df07 = pd.read_parquet('/content/train/1.회원정보/201807_train_회원정보.parquet')
test_member_info_df07 = pd.read_parquet('/content/test/1.회원정보/201807_test_회원정보.parquet')
eda_df = pd.concat([train_member_info_df07, test_member_info_df07])
eda_df.head()

,기준년월,ID,남녀구분코드,연령,Segment,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,201807,TRAIN_000000,2,40대,D,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),22
1,201807,TRAIN_000001,1,30대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18
2,201807,TRAIN_000002,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,20
3,201807,TRAIN_000003,2,40대,D,1,1,0,1,2,...,0,0,0,0개,0개,0개,0개,1,자녀성장(2),17
4,201807,TRAIN_000004,2,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,1,자녀성장(1),15

In [ ]:
eda_df.shape

(500000, 78)

In [ ]:
eda_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500000 entries, 0 to 99999
Data columns (total 78 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   기준년월                500000 non-null  int64
 1   ID                  500000 non-null  object
 2   남녀구분코드              500000 non-null  int64
 3   연령                  500000 non-null  object
 4   Segment             400000 non-null  object
 5   회원여부_이용가능           500000 non-null  int64
 6   회원여부_이용가능_CA        500000 non-null  int64
 7   회원여부_이용가능_카드론       500000 non-null  int64
 8   소지여부_신용             500000 non-null  int64
 9   소지카드수_유효_신용         500000 non-null  int64
 10  소지카드수_이용가능_신용       500000 non-null  int64
 11  입회일자_신용             500000 non-null  int64
 12  입회경과개월수_신용          500000 non-null  int64
 13  회원여부_연체             500000 non-null  int64
 14  이용거절여부_카드론          500000 non-null  int64
 15  동의여부_한도증액안내         500000 non-null  int64
 16  수신거부여부_TM           500000 non-null  int64
 17  수신거부여부_DM           500000 non-null  int64
 18  수신거부여부_메일           500000 non-null  int64
 19  수신거부여부_SMS          500000 non-null  int64
 20  가입통신회사코드            415756 non-null  object
 21  탈회횟수_누적             500000 non-null  int64
 22  최종탈회후경과월            500000 non-null  int64
 23  탈회횟수_발급6개월이내        500000 non-null  int64
 24  탈회횟수_발급1년이내         500000 non-null  int64
 25  거주시도명               500000 non-null  object
 26  직장시도명               448813 non-null  object
 27  마케팅동의여부             500000 non-null  int64
 28  유효카드수_신용체크          500000 non-null  int64
 29  유효카드수_신용            500000 non-null  int64
 30  유효카드수_신용_가족         500000 non-null  int64
 31  유효카드수_체크            500000 non-null  int64
 32  유효카드수_체크_가족         500000 non-null  int64
 33  이용가능카드수_신용체크        500000 non-null  int64
 34  이용가능카드수_신용          500000 non-null  int64
 35  이용가능카드수_신용_가족       500000 non-null  int64
 36  이용가능카드수_체크          500000 non-null  int64
 37  이용가능카드수_체크_가족       500000 non-null  int64
 38  이용카드수_신용체크          500000 non-null  int64
 39  이용카드수_신용            500000 non-null  int64
 40  이용카드수_신용_가족         500000 non-null  int64
 41  이용카드수_체크            500000 non-null  int64
 42  이용카드수_체크_가족         500000 non-null  int64
 43  이용금액_R3M_신용체크       500000 non-null  int64
 44  이용금액_R3M_신용         500000 non-null  int64
 45  이용금액_R3M_신용_가족      500000 non-null  int64
 46  이용금액_R3M_체크         500000 non-null  int64
 47  이용금액_R3M_체크_가족      500000 non-null  int64
 48  _1순위카드이용금액          500000 non-null  int64
 49  _1순위카드이용건수          500000 non-null  int64
 50  _1순위신용체크구분          497291 non-null  object
 51  _2순위카드이용금액          500000 non-null  int64
 52  _2순위카드이용건수          500000 non-null  int64
 53  _2순위신용체크구분          302596 non-null  object
 54  최종유효년월_신용_이용가능      458867 non-null  float64
 55  최종유효년월_신용_이용        400594 non-null  float64
 56  최종카드발급일자            496208 non-null  float64
 57  보유여부_해외겸용_본인        500000 non-null  int64
 58  이용가능여부_해외겸용_본인      500000 non-null  int64
 59  이용여부_3M_해외겸용_본인     500000 non-null  int64
 60  보유여부_해외겸용_신용_본인     500000 non-null  int64
 61  이용가능여부_해외겸용_신용_본인   500000 non-null  int64
 62  이용여부_3M_해외겸용_신용_본인  500000 non-null  int64
 63  연회비발생카드수_B0M        500000 non-null  object
 64  연회비할인카드수_B0M        500000 non-null  int64
 65  기본연회비_B0M           500000 non-null  int64
 66  제휴연회비_B0M           500000 non-null  int64
 67  할인금액_기본연회비_B0M      500000 non-null  int64
 68  할인금액_제휴연회비_B0M      500000 non-null  int64
 69  청구금액_기본연회비_B0M      500000 non-null  int64
 70  청구금액_제휴연회비_B0M      500000 non-null  int64
 71  상품관련면제카드수_B0M       500000 non-null  object
 72  임직원면제카드수_B0M        500000 non-null  object
 73  우수회원면제카드수_B0M       500000 non-null  object
 74  기타면제카드수_B0M         500000 non-null  object
 75  카드신청건수              500000 non-null  int64
 76  Life_Stage          500000 non-null  object
 77  최종카드발급경과월           500000 non-null  int64
dtypes: float64(3), int64(61), object(14)
memory usage: 301.4+ MB

In [ ]:
eda_df.describe()

,기준년월,남녀구분코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,소지카드수_이용가능_신용,입회일자_신용,입회경과개월수_신용,회원여부_연체,이용거절여부_카드론,동의여부_한도증액안내,수신거부여부_TM,수신거부여부_DM,수신거부여부_메일,수신거부여부_SMS,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,탈회횟수_발급1년이내,마케팅동의여부,유효카드수_신용체크,유효카드수_신용,유효카드수_신용_가족,유효카드수_체크,유효카드수_체크_가족,이용가능카드수_신용체크,이용가능카드수_신용,이용가능카드수_신용_가족,이용가능카드수_체크,이용가능카드수_체크_가족,이용카드수_신용체크,이용카드수_신용,이용카드수_신용_가족,이용카드수_체크,이용카드수_체크_가족,이용금액_R3M_신용체크,이용금액_R3M_신용,이용금액_R3M_신용_가족,이용금액_R3M_체크,이용금액_R3M_체크_가족,_1순위카드이용금액,_1순위카드이용건수,_2순위카드이용금액,_2순위카드이용건수,최종유효년월_신용_이용가능,최종유효년월_신용_이용,최종카드발급일자,보유여부_해외겸용_본인,이용가능여부_해외겸용_본인,이용여부_3M_해외겸용_본인,보유여부_해외겸용_신용_본인,이용가능여부_해외겸용_신용_본인,이용여부_3M_해외겸용_신용_본인,연회비할인카드수_B0M,기본연회비_B0M,제휴연회비_B0M,할인금액_기본연회비_B0M,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,카드신청건수,최종카드발급경과월
count,500000.0,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,5.000000e+05,500000.000000,500000.000000,500000.00000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.00000,500000.000000,500000.000000,500000.000000,500000.0,500000.000000,500000.000000,500000.000000,500000.000000,500000.0,500000.000000,500000.000000,500000.000000,500000.000000,458867.000000,400594.000000,4.962080e+05,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.000000,500000.0,500000.000000,500000.000000,500000.0,500000.0,500000.000000,500000.000000,500000.000000,500000.000000
mean,201807.0,1.476792,0.956888,0.887354,0.612322,0.992432,1.252230,1.157478,2.012261e+07,71.237026,0.020752,0.19496,0.097426,0.354716,0.306488,0.310642,0.369070,0.509860,26.346466,0.038726,0.064882,0.810922,2.079528,1.511554,0.035566,0.567974,0.000016,1.955534,1.391170,0.035380,0.564364,0.000006,1.34123,1.178822,0.032380,0.162408,0.0,17638.581832,16024.378486,261.598040,1614.143560,0.0,11885.330110,40.916234,3163.939598,13.931716,202152.017105,202153.863323,2.016485e+07,0.788898,0.758028,0.619526,0.690986,0.640494,0.565604,0.0,0.719882,1.737714,0.0,0.0,0.719882,1.737714,0.155496,19.340410
std,0.0,0.499462,0.203109,0.316160,0.487221,0.086665,0.547404,0.612728,6.044429e+04,72.369804,0.142553,0.39617,0.296537,0.478428,0.461035,0.462757,0.482553,0.665904,37.287713,0.192941,0.246318,0.391571,1.201690,0.827248,0.222794,0.808087,0.004000,1.222633,0.872297,0.222289,0.805247,0.002449,0.95377,0.850766,0.213072,0.376260,0.0,23706.694344,22524.945784,1651.828344,7131.116452,0.0,15068.441319,51.679248,7178.959239,28.636007,115.018172,107.407663,1.149874e+04,0.408091,0.428278,0.485504,0.462087,0.479856,0.495678,0.0,8.628593,40.581298,0.0,0.0,8.628593,40.581298,0.362377,13.447024
min,201807.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.990110e+07,2.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.0,-6762.000000,-6847.000000,0.000000,0.000000,0.0,-3925.000000,-2.000000,-3156.000000,-1.000000,201805.000000,201807.000000,2.013053e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
25%,201807.0,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,2.010030e+07,14.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.00000,1.000000,0.000000,0.000000,0.0,744.000000,0.000000,0.000000,0.000000,0.0,282.000000,2.000000,0.000000,0.000000,202103.000000,202104.000000,2.016023e+07,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,9.000000
50%,201807.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.014070e+07,49.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000,1.00000,1.000000,0.000000,0.000000,0.0,9252.000000,7901.500000,0.000000,0.000000,0.0,6557.500000,18.000000,0.000000,0.000000,202203.000000,202203.000000,2.017021e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,17.000000
75%,201807.0,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.017060e+07,101.000000,0.000000,0.00000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,45.000000,0.000000,0.000000,1.000000,3.000000,2.000000,0.000000,1.000000,0.000000,3.000000,2.000000,0.000000,1.000000,0.000000,2.00000,2.000000,0.000000,0.000000,0.0,23349.000000,20968.000000,0.000000,0.000000,0.0,17310.250000,64.000000,3054.000000,17.000000,202210.000000,202210.000000,2.017102e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,28.000000
max,201807.0,2.000000,1.000000,1.000000,1.000000,1.000000,4.000000,3.000000,2.018060e+07,333.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,112.000000,1.000000,1.000000,1.000000,8.000000,5.000000,2.000000,3.000000,1.000000,8.000000,5.000000,2.000000,3.000000,1.000000,6.00000,5.000000,2.000000,2.000000,0.0,247532.000000,163706.000000,19481.000000,142752.000000,0.0,118507.000000,224.000000,78866.000000,205.000000,202312.000000,202312.000000,2.018073e+07,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,111.000000,950.000000,0.0,0.0,111.000000,950.000000,1.000000,62.000000

In [ ]:
eda_df['연회비할인카드수_B0M'].value_counts(dropna=False)

연회비할인카드수_B0M
0    500000
Name: count, dtype: int64

In [ ]:
'''
25.03.16
이용카드수_체크_가족                      |
이용금액_R3M_체크_가족                    |
연회비할인카드수_B0M                      | ==> 데이터가 모두 같은 값임. => solution) "drop"
할인금액_기본연회비_B0M                   |
할인금액_제휴연회비_B0M                   |
'''